resolver: lts-18.16
extra-deps:
  - hslua-2.1.0
  - hslua-classes-2.1.0
  - hslua-core-2.1.0
  - hslua-marshalling-2.1.0
  - hslua-objectorientation-2.1.0
  - hslua-packaging-2.1.0
  - lua-2.1.0
  - lua-arbitrary-1.0.0
  - pandoc-types-1.22.1
  - tasty-hslua-1.0.1
  - tasty-lua-1.0.1
ghc-options:
  "$locals": -fhide-source-paths
