name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:

jobs:
  build:
    name: GHC ${{ matrix.version.ghc }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version:
          - ghc: '8.6.5'
            cabal: '3.2'
          - ghc: '8.8.4'
            cabal: '3.2'
          - ghc: '8.10.7'
            cabal: '3.2'
            cabalopts: '--constraint="lua +pkg-config"'
          - ghc: '9.0.1'
            cabal: '3.4'
          - ghc: '9.2.1'
            cabal: '3.6'

    steps:
      - uses: actions/checkout@v2

      - name: Install recent cabal/ghc
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.version.ghc }}
          cabal-version: ${{ matrix.version.cabal }}

      - name: Install system Lua
        run: |
          sudo apt update
          sudo apt install lua5.3 liblua5.3-dev

      - uses: actions/cache@v1
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.version.ghc }}-cabal

      - name: Build
        run: |
          cabal update
          cabal build \
            --enable-tests \
            ${{ matrix.version.cabalopts }}

      - name: Test
        run: |
          cabal test --enable-tests \
            ${{ matrix.version.cabalopts }}

  windows:
    name: Windows (stack)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Cache stack global package db
        id:   stack-global-package-db
        uses: actions/cache@v2
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack\'
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}

      - name: Install dependencies
        run: |
          stack update
          stack test --dependencies-only --fast

      - name: Build
        shell: cmd
        run: |
          stack test --no-run-tests --fast

      - name: Test
        shell: cmd
        run: |
          stack test --fast --test-arguments="--ansi-tricks=false"
